rg_api_homepage:
    path:     /
    defaults: { _controller: RgApiBundle:Default:index }

# список городов по региону из куков
rg_api_area_list:
    path:     /cities/
    defaults: { _controller: RgApiBundle:Area:getCities, _format:json }
    methods:  [GET, HEAD]

# подписки
rg_api_product_index:
    path:     /products/
    defaults: { _controller: RgApiBundle:Product:index, _format:json }
    methods:  [GET, HEAD]

# архивы Родины
rg_api_patria_index:
    path:     /patria/
    defaults: { _controller: RgApiBundle:Patria:index, _format:json }
    methods:  [GET, HEAD]

### Заказ
# создать заказ
rg_api_order_create:
    path:     /orders/
    defaults: { _controller: RgApiBundle:Order:create, _format:json }
    methods:  [POST]

# получить квитанцию по номеру заказа
rg_api_get_receipt_by_order:
    path:     /receipt/{enc_id}/
    defaults: { _controller: RgApiBundle:Order:getReceiptByOrderId }
    methods:  [GET, HEAD]
    requirements:
        enc_id: \w+

### Platron
# pg_check_url
rg_api_platron_check_url:
    path:     /platron/check
    defaults: { _controller: RgApiBundle:Platron:checkURL, _format:json }
    methods:  [POST]
# pg_result_url
rg_api_platron_result_url:
    path:     /platron/result
    defaults: { _controller: RgApiBundle:Platron:resultURL, _format:json }
    methods:  [POST]
# success_payment_url
rg_api_success_url:
    path:     /platron/success
    defaults: { _controller: RgApiBundle:Platron:successURL, _format:json }
    methods:  [GET]
# failure_payment_url
rg_api_platron_failure_url:
    path:     /platron/failure
    defaults: { _controller: RgApiBundle:Platron:failureURL, _format:json }
    methods:  [GET]

### Корзина
# просмотреть корзину
rg_api_cart_index:
    path:     /cart/
    defaults: { _controller: RgApiBundle:Cart:index, _format:json }
    methods:  [GET]

# добавить в корзину
rg_api_cart_add:
    path:     /cart/
    defaults: { _controller: RgApiBundle:Cart:add, _format:json }
    methods:  [PATCH]

# удалить из корзины
rg_api_cart_remove:
    path:     /cart/
    defaults: { _controller: RgApiBundle:Cart:remove, _format:json }
    methods:  [DELETE]

# изменить количество экземпляров позиции в корзине
rg_api_cart_update_quantities:
    path:     /cart/quantities/
    defaults: { _controller: RgApiBundle:Cart:update, _format:json }
    methods:  [PATCH]

# очистить корзину
rg_api_cart_empty:
    path:     /cart/
    defaults: { _controller: RgApiBundle:Cart:empty, _format:json }
    methods:  [PUT]
