services:
# Subscribers
    rg_api.session_has_cart_subscriber:
        class: Rg\ApiBundle\EventSubscriber\SessionHasCartSubscriber
        tags:
            - { name: kernel.event_subscriber, event: kernel.controller, method: onKernelController }

# Listeners
#    rg_api.cors_allow_listener:
#        class: Rg\ApiBundle\Listeners\CorsAllowListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

# Services
    rg_api.edition_normalizer:
        class: Rg\ApiBundle\Service\EditionNormalizer
    rg_api.period_timeunit_converter:
        class: Rg\ApiBundle\Service\PeriodTimeunitConverter
    rg_api.product_cost_calculator:
        class: Rg\ApiBundle\Service\ProductCostCalculator
    rg_api.platron:
        class: Rg\ApiBundle\Service\Platron
        arguments:
            - "@monolog.logger.platron"
    rg_api.encryptor:
        class: Rg\ApiBundle\Service\Encryptor
    rg_api.notification_queue:
        class: Rg\ApiBundle\Service\NotificationQueue
    rg_api.cart_controller:
        class: Rg\ApiBundle\Controller\CartController
    rg_api.dev_dumper:
        class: Rg\ApiBundle\Service\DevDumper
    rg_api.price_to_text_converter:
        class: Rg\ApiBundle\Service\PriceToTextConverter
#    rg_api.order_exception_listener:
#        class: Rg\ApiBundle\Listeners\OrderExceptionListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception }
    rg_api.item_name:
        class: Rg\ApiBundle\Service\ItemName
    rg_api.legal_validator:
        class: Rg\ApiBundle\Service\FieldsValidator
        arguments:
            - "@validator"
    rg_api.twig_render:
        class: Rg\ApiBundle\Service\TwigRender
        arguments:
            - "@twig"
