<?php

namespace Rg\ApiBundle\Repository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAreaWithNotEmptyWorkId()
    {
        $qb = $this->createQueryBuilder('a');
        $result = $qb
            ->select('a')
            ->andWhere("a.works_id <> ''")
            ->getQuery()
            ->getResult()
        ;

        return $result;
    }
}
