<?php

namespace Rg\ApiBundle\Repository;

/**
 * GoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodRepository extends \Doctrine\ORM\EntityRepository
{
}
