<?php

namespace Rg\ApiBundle\Repository;

/**
 * IntervalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervalRepository extends \Doctrine\ORM\EntityRepository
{
}
