<?php

namespace Rg\ApiBundle\Repository;

/**
 * LegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalRepository extends \Doctrine\ORM\EntityRepository
{
}
