<?php

namespace Rg\ApiBundle\Repository;

/**
 * MediumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediumRepository extends \Doctrine\ORM\EntityRepository
{
}
