<?php

namespace Rg\ApiBundle\Repository;

/**
 * MonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthRepository extends \Doctrine\ORM\EntityRepository
{
}
