<?php

namespace Rg\ApiBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQueueOfCreated()
    {
        $qb = $this->createQueryBuilder('n');
        $result = $qb
            ->select('n')
            ->where(
                $qb->expr()->andX(
                    $qb->expr()->eq('n.type', ':type'),
                    $qb->expr()->eq('n.state', ":state")
                )
            )
            ->getQuery()
            ->setParameter('type', 'order_created')
            ->setParameter('state', 'queued')
            ->getResult()
        ;

        return $result;
    }

    public function getQueueOfPaid()
    {
        $qb = $this->createQueryBuilder('n');
        $result = $qb
            ->select('n')
            ->where(
                $qb->expr()->andX(
                    $qb->expr()->eq('n.type', ':type'),
                    $qb->expr()->eq('n.state', ":state")
                )
            )
            ->getQuery()
            ->setParameter('type', 'order_paid')
            ->setParameter('state', 'queued')
            ->getResult()
        ;

        return $result;
    }

    public function getQueueOfOFDReceipt()
    {
        $qb = $this->createQueryBuilder('n');
        $result = $qb
            ->select('n')
            ->where(
                $qb->expr()->andX(
                    $qb->expr()->eq('n.type', ':type'),
                    $qb->expr()->eq('n.state', ":state")
                )
            )
            ->getQuery()
            ->setParameter('type', 'ofd_receipt')
            ->setParameter('state', 'queued')
            ->getResult()
        ;

        return $result;
    }
}
