<?php

namespace Rg\ApiBundle\Repository;

/**
 * PatritemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatritemRepository extends \Doctrine\ORM\EntityRepository
{
}
