<?php

namespace Rg\ApiBundle\Repository;

/**
 * PatriffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatriffRepository extends \Doctrine\ORM\EntityRepository
{
}
