<?php

namespace Rg\ApiBundle\Repository;

/**
 * PeriodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodsRepository extends \Doctrine\ORM\EntityRepository
{
}
