<?php

namespace Rg\ApiBundle\Repository;
use Rg\ApiBundle\Entity\Promo;

/**
 * PinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PinRepository extends \Doctrine\ORM\EntityRepository
{
}
