<?php

namespace Rg\ApiBundle\Repository;

/**
 * PostalIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalIndexRepository extends \Doctrine\ORM\EntityRepository
{
}
