<?php

namespace Rg\ApiBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductsWithMinPricesByArea(int $from_front_id)
    {
        $result = $this->createQueryBuilder('p')
            ->select('
                p,
                p.id,
                p.name,
                p.description,
                p.text,
                p.postal_index,
                p.is_kit,
                p.is_archive,
                p.outer_link,
                p.sort
            ')
            ->addSelect('g,t,d,m,z,a,e')
            ->andWhere('a.from_front_id = :from_front_id OR a.from_front_id IS NULL')
            ->leftJoin('p.goods', 'g')
            ->leftJoin('p.tariffs', 't')
            ->leftJoin('t.delivery', 'd')
            ->leftJoin('t.medium', 'm')
            ->leftJoin('t.zone', 'z')
            ->leftJoin('z.areas', 'a')
            ->join('p.editions', 'e')
//            ->groupBy('p,t,d,m,z,a,e')
            ->orderBy('p.sort')
            ->setParameter('from_front_id', $from_front_id)
            ->getQuery()
            ->getResult()
        ;

        return $result;
    }
}
