<?php

namespace Rg\ApiBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductsWithMinPricesByArea(int $from_front_id)
    {
        $dql = <<<DQL
SELECT
    p,
    p.id,
    p.name,
    p.description,
    p.text,
    p.postal_index,
    p.is_kit,
    p.is_archive,
    p.outer_link,
    p.sort,
    min(t.price) AS min_price,
    e,
    t
FROM RgApiBundle:Product p
LEFT JOIN p.tariffs t
LEFT JOIN t.zone z WITH z.from_front_id = :from_front_id
JOIN p.editions e
GROUP BY p.id, e.id, t.id
DQL;

        $query = $this->getEntityManager()->createQuery($dql)
            ->setParameter('from_front_id', $from_front_id)
        ;
        $result = $query->getResult();

        return $result;
    }

}
