<?php

namespace Rg\ApiBundle\Repository;

use Rg\ApiBundle\Controller\Relations;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Rg\ApiBundle\Repository\Relations
{
}
