<?php

namespace Rg\ApiBundle\Repository;

/**
 * PromocodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromocodesRepository extends \Doctrine\ORM\EntityRepository
{
}
