<?php

namespace Rg\ApiBundle\Repository;

/**
 * SummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SummaryRepository extends \Doctrine\ORM\EntityRepository
{
}
