<?php

namespace Rg\ApiBundle\Repository;

/**
 * TariffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TariffRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $product_id
     * @return array
     */
    public function filterByProductId(int $product_id)
    {
        $tariffs = $this->findBy(['product' => $product_id]);

        return $tariffs;
    }

}
