<?php

namespace Rg\ApiBundle\Repository;

/**
 * TariffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TariffRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListByProductId(int $product_id)
    {
        $meta = $this->getClassMetadata();
        var_dump($meta);

        return ;
    }
}
