<?php

namespace Rg\ApiBundle\Repository;

/**
 * TimeunitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeunitRepository extends \Doctrine\ORM\EntityRepository
{
}
