<?php

namespace Rg\ApiBundle\Repository;

/**
 * TimeblockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeblockRepository extends \Doctrine\ORM\EntityRepository
{
}
