Rg\ApiBundle\Entity\Area:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\AreaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
            column: name
    manyToOne:
        zone:
            targetEntity: Zone
            inversedBy: areas
    lifecycleCallbacks: {  }
