Rg\ApiBundle\Entity\Area:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\AreaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
            column: name
        from_front_id:
            type: integer
            column: from_front_id
        ### for transfer from old subsmag
        works_id:
            type: string
            column: works_id
        ### use relations instead
#        parent_region_id:
#            type: string
#            column: parent_region_id
        link:
            type: string
            column: "`link`"
    manyToOne:
        ### not empty means that i'm a little city in the big area
        parent_area:
            targetEntity: Area
            inversedBy: child_areas
        zone:
            targetEntity: Zone
            inversedBy: areas
    oneToMany:
        child_areas:
            targetEntity: Area
            mappedBy: parent_area
        cities:
            targetEntity: City
            mappedBy: area
        sales:
            targetEntity: Sale
            mappedBy: area
    lifecycleCallbacks: {  }
