Rg\ApiBundle\Entity\City:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\CityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
            column: name
        type:
            type: string
            length: '20'
            column: type
        works_cid:
            type: integer
            column: works_cid
    manyToOne:
        area:
            targetEntity: Area
            inversedBy: cities
    oneToMany:
#        legal_addresses:
#            targetEntity: Legal
#            mappedBy: city
        legal_deliveries:
            targetEntity: Legal
            mappedBy: delivery_city
    lifecycleCallbacks: {  }
