Rg\ApiBundle\Entity\Delivery:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\DeliveryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '200'
            column: name
    oneToMany:
        tariffs:
            targetEntity: Tariff
            mappedBy: delivery
    lifecycleCallbacks: {  }
