Rg\ApiBundle\Entity\Good:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\GoodRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start:
            type: date
            column: start
        end:
            type: date
            column: end
        is_regional:
            type: boolean
            column: is_regional
    oneToMany:
        items:
            targetEntity: Item
            mappedBy: good
    manyToOne:
        product:
            targetEntity: Product
            inversedBy: goods
        period:
            targetEntity: Period
            inversedBy: goods
        area:
            targetEntity: Area
            inversedBy: goods
    lifecycleCallbacks: {  }
