Rg\ApiBundle\Entity\Interval:
    type: entity
    table: "`interval`"
    repositoryClass: Rg\ApiBundle\Repository\IntervalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start:
            type: date
            column: start
        end:
            type: date
            column: end
        is_regional:
            type: boolean
            column: is_regional
    manyToOne:
        timeblock:
            targetEntity: Timeblock
            inversedBy: intervals
        area:
            targetEntity: Area
            inversedBy: intervals
    lifecycleCallbacks: {  }
