Rg\ApiBundle\Entity\Item:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\ItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        duration:
            type: smallint
            column: duration
        quantity:
            type: integer
            column: quantity
        timeunit_amount:
            type: integer
            column: timeunit_amount
        discount:
            type: float
            column: discount
        cost:
            type: float
            column: cost
        cat_cost:
            type: float
            column: cat_cost
        del_cost:
            type: float
            column: del_cost
        discounted_cat_cost:
            type: float
            column: discounted_cat_cost
        discounted_del_cost:
            type: float
            column: discounted_del_cost
        total:
            type: float
            column: total
    manyToOne:
        order:
            targetEntity: Order
            inversedBy: items
        month:
            targetEntity: Month
            inversedBy: items
        tariff:
            targetEntity: Tariff
            inversedBy: items
        promo:
            targetEntity: Promo
            inversedBy: items
    lifecycleCallbacks: {  }
