Rg\ApiBundle\Entity\Item:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\ItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        duration:
            type: smallint
            column: duration
        quantity:
            type: integer
            column: quantity
        timeunit_amount:
            type: integer
            column: timeunit_amount
        discount_coef:
            type: float
            column: discount_coef
        cost:
            type: float
            column: cost
    manyToOne:
        order:
            targetEntity: Order
            inversedBy: items
        month:
            targetEntity: Month
            inversedBy: items
        tariff:
            targetEntity: Tariff
            inversedBy: items
        promo:
            targetEntity: Promo
            inversedBy: items
    lifecycleCallbacks: {  }
