Rg\ApiBundle\Entity\Legal:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\LegalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: text
            column: name
        inn:
            type: string
            column: inn
        kpp:
            type: string
            column: kpp
        bank_name:
            type: string
            column: bank_name
        bank_account:
            type: string
            column: bank_account
        bank_corr_account:
            type: string
            column: bank_corr_account
        bik:
            type: string
            column: bik
        postcode:
            type: string
            column: postcode
        city:
            type: string
            column: city
        street:
            type: string
            column: street
            nullable: true
        building_number:
            type: string
            column: building_number
            nullable: true
        building_subnumber:
            type: string
            column: building_subnumber
            nullable: true
        building_part:
            type: string
            column: building_part
            nullable: true
        appartment:
            type: string
            column: appartment
            nullable: true
        contact_name:
            type: string
            column: contact_name
        contact_phone:
            type: string
            column: contact_phone
        contact_fax:
            type: string
            column: contact_fax
            nullable: true
        contact_email:
            type: string
            column: contact_email
        delivery_postcode:
            type: string
            column: delivery_postcode
        delivery_street:
            type: string
            column: delivery_street
            nullable: true
        delivery_building_number:
            type: string
            column: delivery_building_number
            nullable: true
        delivery_building_subnumber:
            type: string
            column: delivery_building_subnumber
            nullable: true
        delivery_building_part:
            type: string
            column: delivery_building_part
            nullable: true
        delivery_appartment:
            type: string
            column: delivery_appartment
            nullable: true
        comment:
            type: string
            column: comment
            nullable: true
    manyToOne:
#        city:
#            targetEntity: City
#            inversedBy: legal_addresses
        delivery_city:
            targetEntity: City
            inversedBy: legal_deliveries
    oneToMany:
        orders:
            targetEntity: Order
            mappedBy: legal
    lifecycleCallbacks: {  }
