Rg\ApiBundle\Entity\Medium:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\MediumRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '200'
            column: name
        alias:
            type: string
            length: '50'
            column: "`alias`"
        description:
            type: text
            length: '500'
            column: description
    oneToMany:
        tariffs:
            targetEntity: Tariff
            mappedBy: medium
        patriffs:
            targetEntity: Patriff
            mappedBy: medium
    lifecycleCallbacks: {  }
