Rg\ApiBundle\Entity\Order:
    type: entity
    table: "`order`"
    repositoryClass: Rg\ApiBundle\Repository\OrderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
            column: date
        name:
            type: string
            column: name
        phone:
            type: string
            column: phone
        address:
            type: text
            length: '1000'
            column: address
        email:
            type: string
            column: email
        total:
            type: float
            column: total
        is_paid:
            type: boolean
            column: is_paid
    manyToOne:
        payment:
            targetEntity: Payment
            inversedBy: orders
        user:
            targetEntity: User
            inversedBy: orders
    oneToMany:
        items:
            targetEntity: Item
            mappedBy: order
        patritems:
            targetEntity: Patritem
            mappedBy: order
    lifecycleCallbacks: {  }
