Rg\ApiBundle\Entity\Order:
    type: entity
    table: "`order`"
    repositoryClass: Rg\ApiBundle\Repository\OrderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
            column: date
        name:
            type: string
            column: name
        phone:
            type: string
            column: phone
        address:
            type: text
            length: '1000'
            column: address
        email:
            type: string
            column: email
        total:
            type: float
            column: total
        is_paid:
            type: boolean
            column: is_paid
        pg_payment_id:
            type: string
            column: pg_payment_id
        comment:
            type: string
            column: comment
            nullable: true
        postcode:
            type: string
            column: postcode
        street:
            type: string
            column: street
            nullable: true
        building_number:
            type: string
            column: building_number
            nullable: true
        building_subnumber:
            type: string
            column: building_subnumber
            nullable: true
        building_part:
            type: string
            column: building_part
            nullable: true
        appartment:
            type: string
            column: appartment
            nullable: true
    manyToOne:
        payment:
            targetEntity: Payment
            inversedBy: orders
        user:
            targetEntity: User
            inversedBy: orders
        legal:
            targetEntity: Legal
            inversedBy: orders
        city:
            targetEntity: City
            inversedBy: orders
    oneToMany:
        items:
            targetEntity: Item
            mappedBy: order
        patritems:
            targetEntity: Patritem
            mappedBy: order
        notifications:
            targetEntity: Notification
            mappedBy: order
    oneToOne:
        pin:
            targetEntity: Pin
            mappedBy: order
    lifecycleCallbacks: {  }
