Rg\ApiBundle\Entity\Patritem:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\PatritemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: integer
            column: quantity
        cost:
            type: float
            column: cost
        cat_cost:
            type: float
            column: cat_cost
        del_cost:
            type: float
            column: del_cost
        discounted_cat_cost:
            type: float
            column: discounted_cat_cost
        discounted_del_cost:
            type: float
            column: discounted_del_cost
        total:
            type: float
            column: total
    manyToOne:
        order:
            targetEntity: Order
            inversedBy: patritems
        patriff:
            targetEntity: Patriff
            inversedBy: patritems
    lifecycleCallbacks: {  }
