Rg\ApiBundle\Entity\Period:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\PeriodRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
            column: name
        year:
            type: smallint
            column: year
    oneToMany:
        tariffs:
            targetEntity: Tariff
            mappedBy: period
    lifecycleCallbacks: {  }
