Rg\ApiBundle\Entity\Period:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\PeriodRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        first_month:
            type: smallint
            column: first_month
        duration:
            type: smallint
            column: duration
        year:
            type: smallint
            column: year
    oneToMany:
        goods:
            targetEntity: Good
            mappedBy: period
    lifecycleCallbacks: {  }
