Rg\ApiBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
            column: name
        description:
            type: text
            column: description
        postal_index:
            type: string
            length: '10'
            column: postal_index
        is_active:
            type: boolean
            column: is_active
        is_archive:
            type: boolean
            column: is_archive
        outer_link:
            type: text
            column: outer_link
        is_kit:
            type: boolean
            column: is_kit
        sort:
            type: smallint
            column: sort
    oneToMany:
        tariffs:
            targetEntity: Tariff
            mappedBy: product
    manyToMany:
        editions:
            targetEntity: Edition
            inversedBy: products
    lifecycleCallbacks: {  }
