Rg\ApiBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
            column: name
        description:
            type: text
            column: description
        text:
            type: text
            column: "`text`"
        is_active:
            type: boolean
            column: is_active
        is_archive:
            type: boolean
            column: is_archive
        outer_link:
            type: text
            column: outer_link
        is_kit:
            type: boolean
            column: is_kit
        is_popular:
            type: boolean
            column: is_popular
        sort:
            type: smallint
            column: sort
    oneToMany:
        tariffs:
            targetEntity: Tariff
            mappedBy: product
        postal_indexes:
            targetEntity: PostalIndex
            mappedBy: product
        sales:
            targetEntity: Sale
            mappedBy: product
    manyToMany:
        editions:
            targetEntity: Edition
            inversedBy: products
    lifecycleCallbacks: {  }
