Rg\ApiBundle\Entity\Sale:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\SaleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start:
            type: date
            column: start
        end:
            type: date
            column: end
        is_regional:
            type: boolean
            column: is_regional
        is_main:
            type: boolean
            column: is_main
    manyToOne:
        product:
            targetEntity: Product
            inversedBy: sales
        month:
            targetEntity: Month
            inversedBy: sales
        area:
            targetEntity: Area
            inversedBy: sales
    lifecycleCallbacks: {  }
