Rg\ApiBundle\Entity\Subscribes:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\SubscribesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        namePeriodId:
            type: integer
            column: name_period_id
        areaId:
            type: integer
            column: area_id
        subscribePeriodStart:
            type: datetime
            column: subscribe_period_start
        subscribePeriodEnd:
            type: datetime
            column: subscribe_period_end
        periodId:
            type: smallint
            column: period_id
    lifecycleCallbacks: {  }
