Rg\ApiBundle\Entity\Tariff:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\TariffRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        price:
            type: float
            column: price
    oneToMany:
        items:
            targetEntity: Item
            mappedBy: tariff
    manyToOne:
        product:
            targetEntity: Product
            inversedBy: tariffs
        timeunit:
            targetEntity: Timeunit
            inversedBy: tariffs
        delivery:
            targetEntity: Delivery
            inversedBy: tariffs
        zone:
            targetEntity: Zone
            inversedBy: tariffs
        medium:
            targetEntity: Medium
            inversedBy: tariffs
    lifecycleCallbacks: {  }
