Rg\ApiBundle\Entity\Tariff:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\TariffRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        price:
            type: float
            column: price
    manyToMany:
        orders:
            targetEntity: Order
            mappedBy: tariffs
    manyToOne:
        product:
            targetEntity: Product
            inversedBy: tariffs
        period:
            targetEntity: Period
            inversedBy: tariffs
        delivery:
            targetEntity: Delivery
            inversedBy: tariffs
        zone:
            targetEntity: Zone
            inversedBy: tariffs
        media:
            targetEntity: Media
            inversedBy: tariffs
    lifecycleCallbacks: {  }
