Rg\ApiBundle\Entity\Timeblock:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\TimeblockRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        first_month:
            type: smallint
            column: first_month
        duration:
            type: smallint
            column: duration
        year:
            type: smallint
            column: year
    oneToMany:
        intervals:
            targetEntity: Interval
            mappedBy: timeblock
    manyToMany:
        tariffs:
            targetEntity: Tariff
            inversedBy: timeblocks
        orders:
            targetEntity: Order
            mappedBy: timeblocks
    lifecycleCallbacks: {  }
