Rg\ApiBundle\Entity\Zones:
    type: entity
    table: null
    repositoryClass: Rg\ApiBundle\Repository\ZonesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        zoneNumber:
            type: smallint
            column: zone_number
        areaId:
            type: smallint
            column: area_id
        tarifId:
            type: integer
            column: tarif_id
    lifecycleCallbacks: {  }
