<?php

namespace Rg\SubsmagBundle\Repository;

/**
 * ActionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionsRepository extends \Doctrine\ORM\EntityRepository
{
}
