<?php

namespace Rg\SubsmagBundle\Repository;

/**
 * AreasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreasRepository extends \Doctrine\ORM\EntityRepository
{
}
