<?php

namespace Rg\SubsmagBundle\Repository;

/**
 * KitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KitsRepository extends \Doctrine\ORM\EntityRepository
{
}
