<?php

namespace Rg\SubsmagBundle\Repository;

/**
 * SubscribesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribesRepository extends \Doctrine\ORM\EntityRepository
{
}
