<?php

namespace Rg\SubsmagBundle\Repository;

/**
 * ZonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZonesRepository extends \Doctrine\ORM\EntityRepository
{
}
