Rg\SubsmagBundle\Entity\Areas:
    type: entity
    table: subsmag.areas
    repositoryClass: Rg\SubsmagBundle\Repository\AreasRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        areaName:
            type: string
            length: '50'
            column: area_name
    lifecycleCallbacks: {  }
