Rg\SubsmagBundle\Entity\Kits:
    type: entity
    table: subsmag.kits
    repositoryClass: Rg\SubsmagBundle\Repository\KitsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nameKit:
            type: string
            length: 255
            column: name_kit
        flagSubscribe:
            type: boolean
            column: flag_subscribe
    lifecycleCallbacks: {  }
