Rg\SubsmagBundle\Entity\Orders:
    type: entity
    table: subsmag.orders
    repositoryClass: Rg\SubsmagBundle\Repository\OrdersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        productId:
            type: integer
            type: integer
            column: product_id
        kitId:
            type: integer
            type: integer
            column: kit_id
        zoneId:
            type: integer
            column: zone_id
        subscribeId:
            type: integer
            column: subscribe_id
        date:
            type: datetime
            column: date
        address:
            type: string
            length: 255
            column: address
        price:
            type: decimal
            column: price
        flagPaid:
            type: boolean
            column: flag_paid
    lifecycleCallbacks: {  }
