Rg\SubsmagBundle\Entity\Subscribes:
    type: entity
    table: subsmag.subscribes
    repositoryClass: Rg\SubsmagBundle\Repository\SubscribesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        namePeriodId:
            type: integer
            column: name_period_id
        areaId:
            type: integer
            column: area_id
        subscribePeriodStart:
            type: datetime
            column: subscribe_period_start
        subscribePeriodEnd:
            type: datetime
            column: subscribe_period_end
        periodId:
            type: integer
            column: period_id
    lifecycleCallbacks: {  }
