Rg\SubsmagBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: Rg\SubsmagBundle\Repository\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        login:
            type: string
            length: '128'
            column: login
        password:
            type: string
            length: 255
            column: password
        userKey:
            type: string
            length: '255'
            column: user_key
        dateRegistration:
            type: datetime
            column: date_registration
        dateLastlogin:
            type: datetime
            column: date_lastlogin
        flagCanRest:
            type: boolean
            column: flag_can_rest
    lifecycleCallbacks: {  }
