Rg\SubsmagBundle\Entity\Zones:
    type: entity
    table: subsmag.zones
    repositoryClass: Rg\SubsmagBundle\Repository\ZonesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        zoneNumber:
            type: smallint
            column: zone_number
        tarifId:
            type: integer
            column: tarif_id
    lifecycleCallbacks: {  }
