rg_api:
    resource: "@RgApiBundle/Resources/config/routing.yml"
    prefix:   /api/

##################
## The secret way to work with vue SPA
## Ask nobody please about why this is like this is.
##################
fallback:
    path: /{req}
    defaults: { _controller: 'AppBundle:Default:index' }
    requirements:
        req: ".+"

root:
    path: /
    defaults: { _controller: 'AppBundle:Default:index' }
