actions_index:
    path:     /
    defaults: { _controller: "RgSubsmagBundle:Actions:index" }
    methods:  GET

actions_show:
    path:     /{id}/show
    defaults: { _controller: "RgSubsmagBundle:Actions:show" }
    methods:  GET

actions_new:
    path:     /new
    defaults: { _controller: "RgSubsmagBundle:Actions:new" }
    methods:  [GET, POST]

actions_edit:
    path:     /{id}/edit
    defaults: { _controller: "RgSubsmagBundle:Actions:edit" }
    methods:  [GET, POST]

actions_delete:
    path:     /{id}/delete
    defaults: { _controller: "RgSubsmagBundle:Actions:delete" }
    methods:  DELETE
