#products_index:
#    path:     /
#    defaults: { _controller: "RgSubsmagBundle:Products:index" }
#    methods:  GET
#
#products_show:
#    path:     /{id}/show
#    defaults: { _controller: "RgSubsmagBundle:Products:show" }
#    methods:  GET
#
#products_new:
#    path:     /new
#    defaults: { _controller: "RgSubsmagBundle:Products:new" }
#    methods:  [GET, POST]
#
#products_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "RgSubsmagBundle:Products:edit" }
#    methods:  [GET, POST]
#
#products_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "RgSubsmagBundle:Products:delete" }
#    methods:  DELETE
