#promocodes_index:
#    path:     /
#    defaults: { _controller: "RgSubsmagBundle:Promocodes:index" }
#    methods:  GET
#
#promocodes_show:
#    path:     /{id}/show
#    defaults: { _controller: "RgSubsmagBundle:Promocodes:show" }
#    methods:  GET
#
#promocodes_new:
#    path:     /new
#    defaults: { _controller: "RgSubsmagBundle:Promocodes:new" }
#    methods:  [GET, POST]
#
#promocodes_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "RgSubsmagBundle:Promocodes:edit" }
#    methods:  [GET, POST]
#
#promocodes_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "RgSubsmagBundle:Promocodes:delete" }
#    methods:  DELETE
